### ISSUE TITLE
Sip Message Event

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-sdk#111]
We have an usecase in our App for which I need to send a  Sip Message Event with some additional Custom Headers  and Content Type.I am using message.setContentType and message.addCustomHeader.But I am getting 2 content headers in my outgoing Sip Message Event.

Trace of Request
```
MESSAGE sip:mcx.test-111.iitb@192.168.0.104 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.103:39456;branch=z9hG4bK.WhufJ5m0I;rport
From: <sip:mcx.test-111.iitb@192.168.0.103>;tag=gPTMteVWy
To: sip:mcx.test-111.iitb@192.168.0.104
CSeq: 20 MESSAGE
Call-ID: gj53EySfKC
Max-Forwards: 70
Supported: replaces, outbound, gruu
Date: Mon, 01 Feb 2021 08:09:23 GMT
Content-Type: text/plain
Content-Length: 708
User-Agent: NonMCLinphoneAndroid/4.4.0 (Nokia 6.1 Plus) LinphoneSDK/4.5.0-beta.58+5dafa37 (remotes/origin/release/4.5)


Content-Type: application/vnd.3gpp.mcptt-location-info+xml
Content-Length:540
P-Preferred-Identity:<sip:mcx.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org>

<?xml version="1.0" encoding="UTF-8"?>
<location-info xmlns="urn:3gpp:ns:mcpttLocationInfo:1.0">
<Report ReportType="NonEmergency" ReportID="7dda64d1-5830-1235-3f95-525400f2984b">
<CurrentLocation>
<MbmsSaId type="Normal">
<SaId>2</SaId>
</MbmsSaId>
<MbsfnArea type="Normal">
<MbsfnAreaId>1</MbsfnAreaId>
</MbsfnArea>
<CurrentCoordinate>
<longitude type="Normal">
<threebytes>null</threebytes>
</longitude>
<latitude type="Normal">
<threebytes>null</threebytes>
</latitude>
</CurrentCoordinate>
</CurrentLocation>
</Report>
</location-info>

```
Thanks in advance for the help.

**Comment by Viish** [comment]
Please attach the code you use to create & send the message.

**Comment by nick2601** [comment]
> Please attach the code you use to create & send the message.

```
Core core = LinphoneManager.getCore();
ProxyConfig proxyConfig = core.getDefaultProxyConfig();
Address address = proxyConfig.getIdentityAddress();
ChatRoom room = core.getChatRoom(address);
ChatMessage message = room.createEmptyMessage();
message.setContentType("app/info.xml");
message.addCutomHeader("abc","xyz");
if (room != null) {
String msg ="Some Content Body";
message.setUtf8Text(msg);
}
message.send;
```

**Comment by Viish** [comment]
Try adding the content type and custom header after the `setUtf8Text()` line.
Also note that `setUtf8Text()` isn't the right method to call, instead use `addUtf8TextContent()`

**Comment by Viish** [comment]
Can I close the issue?

**Comment by nick2601** [comment]
> Can I close the issue?

1.There still some issue with the addCustomHeader method it does allows us to add special characters like "<",">","@",etc
For eg: I have to send an outgoing Sip Message event with some extra header such as  message.addCustomHeader("Identity","<abc@org>"),when see the sip trace I could not see "<",">".
@Viish Is there a callback for consuming incoming sip MESSAGE content body into the app,I have used the onMessageReceived Call from the Core ,but still I am not able to see Incoming Message Body(some xml content).

**Comment by Viish** [comment]
> Is there another callback for consuming incoming sip MESSAGE content body into the app, I have used the onMessageReceived Call from the Core ,but still I am not able to see Incoming Message Body(some xml content).

No, this is the way. If you aren't called in this, means your message is probably discarded for some reason.

>  For eg: I have to send an outgoing Sip Message event with some extra header such as message.addCustomHeader("Identity","abc@org"),when I see the sip trace, I cant see "<",">" characters.

As always please provide logs showing the issue.

**Comment by nick2601** [comment]
@Viish 
1.I have called CoreListener callback for incoming Sip Message onMessageReceived with the required content type for a multipart body as message.getContentType("multipart/mixed") and tried to fetch the incoming xml content through message.getUtf8Text(),but it seems that I am unable to retrieve the incoming sip message in the app.I have also added the support for getting the contents of the multipart body with some additional content type headers.

Logs from Sdk
 
```
 2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: MESSAGE sip:mcx.test-111.iitb@172.27.233.13:45868;transport=udp SIP/2.0
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Via: SIP/2.0/UDP 172.31.37.34:7684;rport;branch=z9hG4bK3vey20SjNaQ0e
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Max-Forwards: 70
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: From: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org>;tag=get8jHrZQg51j
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: To: <sip:mcx.test-111.iitb@172.27.233.13:45868>;transport=udp
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Call-ID: bd0a36ae-e53e-1239-5091-02b8834228f2
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: CSeq: 31871376 MESSAGE
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mcptt";require;explicite
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: User-Agent: MCLabs Location Server
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Content-Type: multipart/mixed;boundary=177855f151e-cabae03e-177855f151e-875427566547
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Content-Length: 1395
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: P-Asserted-Service: urn:urn-7:3gpp-service.ims.icsi.mcptt
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: P-Asserted-Identity: <sip:mcx.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org>
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: --177855f151e-cabae03e-177855f151e-875427566547
2021-02-09 11:29:00.520 23101-23101/org.linphone.debug I/Linphone: Content-Type: application/vnd.3gpp.mcptt-info+xml
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: Content-Length: 311
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: <?xml version="1.0" encoding="UTF-8"?><mcpttinfo xmlns="urn:3gpp:ns:mcpttInfo:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><mcptt-Params><mcptt-request-uri type="Normal"><mcpttURI>"sip:mcptt.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org"</mcpttURI></mcptt-request-uri></mcptt-Params></mcpttinfo>
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: --177855f151e-cabae03e-177855f151e-875427566547
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: Content-Type: application/vnd.3gpp.mcptt-location-info+xml
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: Content-Length: 772
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: <?xml version="1.0" encoding="UTF-8"?><location-info xmlns="urn:3gpp:ns:mcpttILocationInfo:1.0"><Configuration><NonEmergencyLocationInformation><ServingEcgi/><NeighbouringEcgi/><MbmsSaId/><MbsfnArea/><GeographicalCordinate/><minimumIntervalLength>5</minimumIntervalLength></NonEmergencyLocationInformation><TriggeringCriteria><CellChange><AnyCellChange TriggerId="AnyCellChange"/></CellChange><TrackingAreaChange><AnyTrackingAreaChange TriggerId="AnyTrackingAreaChange"/></TrackingAreaChange><PlmnChange><AnyPlmnChange TriggerId="AnyPlmnChange"/></PlmnChange><PeriodicReport TriggerId="Periodic">10</PeriodicReport><GeographicalAreaChange><AnyAreaChange TriggerId="177855f151e"></AnyAreaChange></GeographicalAreaChange></TriggeringCriteria></Configuration></location-info>
2021-02-09 11:29:00.521 23101-23101/org.linphone.debug I/Linphone: --177855f151e-cabae03e-177855f151e-875427566547--
2021-02-09 11:29:00.555 23101-23101/org.linphone.debug I/Linphone: channel [0x725a736240] [759] bytes parsed
2021-02-09 11:29:00.559 23101-23101/org.linphone.debug W/Linphone: belle_sip_multipart_body_handler [0x724bb627c0]: no new-line after boundary
2021-02-09 11:29:00.559 23101-23101/org.linphone.debug I/Linphone: channel [0x725a736240] read [1395] bytes of body from [172.31.37.34:7684]
2021-02-09 11:29:00.566 23101-23101/org.linphone.debug I/Linphone: bellesip_wake_lock_acquire(): Android wake lock [belle-sip transaction(0x724bb62860)] acquired [ref=0x334a]
2021-02-09 11:29:00.568 23101-23101/org.linphone.debug I/Linphone: bellesip_wake_lock_acquire(): cast long of wakelock 13130
2021-02-09 11:29:00.568 23101-23101/org.linphone.debug I/Linphone: transaction [0x724bb62860]: starting transaction background task with id=[334a].
2021-02-09 11:29:00.568 23101-23101/org.linphone.debug I/Linphone: Changing [server] [MESSAGE] transaction [0x724bb62860], from state [INIT] to [TRYING]
2021-02-09 11:29:00.569 23101-23101/org.linphone.debug E/Linphone: body handler [0x724bb627c0] transfered only [1397] bytes while [2739] were expected
2021-02-09 11:29:00.569 23101-23101/org.linphone.debug I/Linphone: Found chat room in RAM for conference ID ConferenceId(peer=IdentityAddress(sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org), local=IdentityAddress(sip:mcx.test-111.iitb@172.27.233.13)).
2021-02-09 11:29:00.573 23101-23101/org.linphone.debug I/Linphone: Chat message 0x72397b7380: moving from Idle to Delivered
2021-02-09 11:29:00.573 23101-23101/org.linphone.debug I/Linphone: Found chat room in RAM for conference ID ConferenceId(peer=IdentityAddress(sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org), local=IdentityAddress(sip:mcx.test-111.iitb@172.27.233.13)).
2021-02-09 11:29:00.575 23101-23101/org.linphone.debug E/Linphone: Unsupported content-type: application/vnd.3gpp.mcptt-info+xml
2021-02-09 11:29:00.575 23101-23101/org.linphone.debug E/Linphone: Unsupported content-type: application/vnd.3gpp.mcptt-location-info+xml
2021-02-09 11:29:00.575 23101-23101/org.linphone.debug E/Linphone: No content-type in the contents list is supported...
```

2.The Outgoing Sip message which I have constructed and which is going correctly for a given IP address ,but when it is replaced by domain name it is not accepted on our remote server ,whereas the publish ,subscribe are going out correctly
If you take a look at from header of the sip message event , it should go as From: <sip:username@domainname> , but in my case it is going as <sip:username@ipaddress>
[602280ea3064f_28d963d54c90502c368a.gz](https://github.com/BelledonneCommunications/linphone-sdk/files/5953776/602280ea3064f_28d963d54c90502c368a.gz)

**Comment by Viish** [comment]
> 2021-02-09 11:29:00.575 23101-23101/org.linphone.debug E/Linphone: No content-type in the contents list is supported...

This means you are using a ContentType that our SDK doesn't know how to handle. To handle it yourself in your app like you intend to, use `core.addContentTypeSupport()` method.

**Comment by Viish** [comment]
For your second issue, problem seems to be the device fails to resolve the domain name "ims.mnc001.mcc001.3gppnetwork.org".
It works for the REGISTER because it's sent to a local machine: "192.168.0.104:8642"
Check your proxy config, specifically server & route parameters (also known as Outbound Proxy).

**Comment by nick2601** [comment]
> > 2021-02-09 11:29:00.575 23101-23101/org.linphone.debug E/Linphone: No content-type in the contents list is supported...
> 
> This means you are using a ContentType that our SDK doesn't know how to handle. To handle it yourself in your app like you intend to, use `core.addContentTypeSupport()` method.

@Viish I could not find method under core.addContentTypeSupport() under the core class.
I am using library version 4.5.0

**Comment by Viish** [comment]
Indeed the method wasn't properly wrapped, it is now fixed: http://linphone.org/snapshots/docs/liblinphone/4.5/java/org/linphone/core/Core.html#addContentTypeSupport-java.lang.String-
You need a SDK at least 4.5.0-beta.73+4a5c915.

**Comment by nick2601** [comment]
> Indeed the method wasn't properly wrapped, it is now fixed: http://linphone.org/snapshots/docs/liblinphone/4.5/java/org/linphone/core/Core.html#addContentTypeSupport-java.lang.String-
> You need a SDK at least 4.5.0-beta.73+4a5c915.
@Viish 
1)Inspite of adding core.addContentType() method support for the incoming Sip Message I am not able to consume the incoming Sip  message ,I am still getting Unsupported Content Type Header Error.
Apart from that  when my Message is rejected , a new Sip Message is generated automatically(I am not generating this event) ,and sent to server with some weird string in the content body causing to crash the server.

2) Whenever I deregister an account and try to register with the same account a Subscribe Event is generated for 
<sip:rls@linphone.org>

Logs for the same with some [screenshots](https://www.linphone.org:444//tmp/602e2f17ed796_24b09505144b4a840fd3.gz)
![RejectedMessage on Client](https://user-images.githubusercontent.com/59530213/108343109-924d3800-7201-11eb-96cf-0823e64665b7.png)
![AutogeneratedMessageWithWeirdString](https://user-images.githubusercontent.com/59530213/108343137-99744600-7201-11eb-875a-79856e4b3e20.png)
![SipMessageFromServer](https://user-images.githubusercontent.com/59530213/108343261-c0327c80-7201-11eb-90a4-870e0210c9c5.png)
![SipSubscribe](https://user-images.githubusercontent.com/59530213/108343289-c7f22100-7201-11eb-9414-8d6fc82ec0bc.png)

**Comment by Viish** [comment]
> Inspite of adding core.addContentType() method support for the incoming Sip Message I am not able to consume the incoming Sip message ,I am still getting Unsupported Content Type Header Error

You probably misconfigured the content-type. Please attach logs showing the issue.

> Apart from that when my Message is rejected , a new Sip Message is generated automatically(I am not generating this event) ,and sent to server with some weird string in the content body causing to crash the server.

I think you are talking of the IMDN xml message sent to acknowledge reception/display of chat message. If you don't want such messages, use the following configuration:
```
[sip]
im_notif_policy=none
```

> Whenever I deregister an account and try to register with the same account a Subscribe Event is generated for sip:rls@linphone.org

Simply remove this entry from your config file or set it empty like:
```
[sip]
rls_uri=
```

Finally please don't open a ticket on each project we have with the same problem, one ticket per issue is enough.

**Comment by nick2601** [comment]
> You probably misconfigured the content-type. Please attach logs showing the issue.
1)I have added the supported for the content type using `core.addContentTypeSupport`,still getting unsupported content-type error.

2)From Logs ,if you can see I get a 200 Ok for an outgoing subscribe with` Call Id- jc7mdh9zF1`,for which I am expected to get a Notify response which I am listening on onNotifyReceived callback but it looks like  I am not able to receive the Notify Response on Linphone.I have verified from the Server Side that a notify is being sent out ,but I am not able to see it.
[Logs for the same:](https://www.linphone.org:444//tmp/6034ab712d289_4c80baf4d156c8bccad6.gz)

**Comment by Viish** [comment]
> 1)I have added the supported for the content type using core.addContentTypeSupport,still getting unsupported content-type error.

Are you using the following after the core has been initialized?
```
core.addContentTypeSupport("application/vnd.3gpp.mcptt-info+xml")
core.addContentTypeSupport("application/vnd.3gpp.mcptt-location-info+xml")
```

> I have verified from the Server Side that a notify is being sent out ,but I am not able to see it.

You are connected to your proxy through UDP, which means packets can get lost. Try again with TCP or TLS.

**Comment by nick2601** [comment]
> > 1)I have added the supported for the content type using core.addContentTypeSupport,still getting unsupported content-type error.
> 
> Are you using the following after the core has been initialized?
> 
> ```
> core.addContentTypeSupport("application/vnd.3gpp.mcptt-info+xml")
> core.addContentTypeSupport("application/vnd.3gpp.mcptt-location-info+xml")
 ```
Yes I am using after the core has been initialised

**Comment by Viish** [comment]
Try to wait until core is started then.
We have regression tests for that and they are OK.

**Comment by nick2601** [comment]
@Viish 
Thanks for the help and I was able to get a 200 ok for the incoming message,but I have some issues in reading it.
In the onMessageReceived callback I am not able to see the contents of the message body using message.getUTF8text ,since my incoming message has a multipart body , I am using 
```
room.allowMultipart();
message.getChatRoom();
android.util.Log.d(TAG, message.getUtf8Text());
```
Do you have any suggestions for reading the message content using different method.
![SipMessageFromServer](https://user-images.githubusercontent.com/59530213/108343261-c0327c80-7201-11eb-90a4-870e0210c9c5.png)

**Comment by Viish** [comment]
Use the following:
```
for (content in chatMessage.contents) {
    android.util.Log.d(TAG, content.utf8Text);
}
```

**Comment by nick2601** [comment]
@Viish 
1)I am able to see a 200 ok for the Incoming Message from server(sent from server  and accepted on client) but I am not see the contents  in received message nor able to read it on the logcat console ,I am using this method suggested by you
```
 public void onMessageReceived(
                            @NonNull Core core,
                            @NonNull ChatRoom chatRoom,
                            @NonNull ChatMessage message) {
                        chatRoom.allowMultipart();
                        for (Content c : message.getContents()) {
                                c.isMultipart();
                                android.util.Log.d(TAG, c.getUtf8Text());
                            }
                        
}
```
 [Logs for the same](https://www.linphone.org:444//tmp/6037b8a3952fb_a1da6b6ceff6468c725e.gz)

2)I am also not able to receive the notify response sent from the server in app, for a successful subscriptions,I am using this callback
![NotifyResponse](https://user-images.githubusercontent.com/59530213/109172001-52112b00-77a8-11eb-98fd-816c10e504aa.png)


```
@Override
                    public void onNotifyReceived(
                            @NonNull Core core,
                            @NonNull Event linphoneEvent,
                            @NonNull String notifiedEvent,
                            @NonNull Content body) {
                        super.onNotifyReceived(core, linphoneEvent, notifiedEvent, body);
                        linphoneEvent.acceptSubscription();
                        linphoneEvent.getSubscriptionState();
                        if (notifiedEvent == "presence"
                                || body.getType() == "application"
                                || body.getSubtype() == "pidf/xml") {
                            String notifyResponse = body.getStringBuffer();
                            android.util.Log.d(TAG, notifyResponse);
                            android.util.Log.d(TAG, body.getUtf8Text());
                        }
                    }
```
Thanks in advance for your valuable suggestions.:)

**Comment by Viish** [comment]
1) There is no message received in the logs you attached

2) No NOTIFY in the logs either.

**Comment by nick2601** [comment]
> 1. There is no message received in the logs you attached
> 2. No NOTIFY in the logs either

Sorry, I didnt notice that , Please take a look at this logs
[Logs](https://www.linphone.org:444//tmp/6038256d9998b_721ce0aae068031734fc.gz)

The notify response is not there in this logs.
I have question ,Lets say I am receiving a certain message from a SipUri which is not my contact will I receive the message?
Do I need to create chatroom  with the intended sip address from which I am expecting a Sip Message, or the stack handles automatically?
I have this scenario currently that I need to  send some a Sip Message Event to abc@myorganization.com and receive a response from the different sip address such as xyz@myorganization.com.
Should I use core.findChatRoom method to specify addresses in onMessageReceived callback or create a different function to handle this.

**Comment by Viish** [comment]
As you can see in the following logs:
```
2021-02-26 03:52:20:857 [org.linphone.debug/liblinphone] MESSAGE Insert new content type in database: `application/vnd.3gpp.mcptt-info+xml`.
2021-02-26 03:52:20:857 [org.linphone.debug/liblinphone] MESSAGE Insert new content type in database: `application/vnd.3gpp.mcptt-location-info+xml`.
2021-02-26 03:52:20:884 [org.linphone.debug/linphone-android] WARNING [Notifications Manager] Message has no text or file transfer information to display, ignoring it...
```
Multipart is correctly parsed, each content is stored in the database so chatMessage.getContents() will return both, and the app is notified of the received message.

Regarding your NOTIFY, we don't support out of dialog presence NOTIFY.

> I have question ,Lets say I am receiving a certain message from a SipUri which is not my contact will I receive the message?
Do I need to create chatroom with the intended sip address from which I am expecting a Sip Message, or the stack handles automatically?

No, you don't have to do anything. If you receive a MESSAGE from a different SIP URI that the one you used to send a message to, a new chat room will be created automatically, and you will be notified of the new chatroom/message in the onMessageReceived callback.

**Comment by nick2601** [comment]
> Regarding your NOTIFY, we don't support out of dialog presence NOTIFY.


@Viish 
1)Can you explain me what is exactly out of dialog presence NOTIFY, and why it is ignored.
As per my understanding if the **Call ID** and **Event** from the second SUBSCRIBE request is matched correctly  with the NOTIFY response going out from server , the Linphone Stack should process it .
Can you provide me some insights how should I handle this issue with respect from server side.

2)Now for the Sip Message ,why I am getting this 
`2021-02-26 18:57:39.983 16685-16685/org.linphone.debug E/Linphone: body handler [0x723b5f1d00] transfered only [1399] bytes while [2743] were expected
`
Inspite of using chatMessage.getContents() ,I am able to read the contents of  `application/vnd.3gpp.mcptt-info+xml` and the contents of `application/vnd.3gpp.mcptt-location-info+xml` are still being ignored.
I would very likely to have your suggestion on this also.

Thanks in advance for your suggestion.

**Comment by Viish** [comment]
> As per my understanding if the Call ID and Event from the second SUBSCRIBE request is matched correctly with the NOTIFY response going out from server , the Linphone Stack should process it .

Yes, but the To header of the NOTIFY doesn't match the FROM of the subscribe, hence the out of dialog.

> why I am getting this

That happens if the Content-Length header doesn't match the content length, but that shouldn't be a problem anyway.

> I am able to read the contents of application/vnd.3gpp.mcptt-info+xml and the contents of application/vnd.3gpp.mcptt-location-info+xml are still being ignored.

You are able to read one but not the other?

**Comment by nick2601** [comment]
> You are able to read one but not the other?
Yeah I was able to read one and not the other:(

**Comment by Viish** [comment]
Weird. I just added a test to our test suite for your case, it works. Check out liblinphone branch `feature/add_generic_content_method`

**Comment by nick2601** [comment]
> Weird. I just added a test to our test suite for your case, it works. Check out liblinphone branch `feature/add_generic_content_method`

@Viish I was able to read both contents ,we need to use 
c.getUtf8text instead of message.getUtf8text

**Comment by nick2601** [comment]
> > As per my understanding if the Call ID and Event from the second SUBSCRIBE request is matched correctly with the NOTIFY response going out from server , the Linphone Stack should process it .
> 
> Yes, but the To header of the NOTIFY doesn't match the FROM of the subscribe, hence the out of dialog.

@Viish But the **To** header of the NOTIFY matches with **Contact Address** of the SIP SUBSCRIBE 
```
SUBSCRIBE sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Via: SIP/2.0/UDP 172.27.232.105:44263;branch=z9hG4bK.MQV1wJ3DG;rport
From: <sip:mcx.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org>;tag=Ux9dIH7eh
To: sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org
CSeq: 20 SUBSCRIBE
Call-ID: sVhwxkU8Xr
Max-Forwards: 70
Route: <sip:172.31.37.34:7684;lr>
Supported: replaces, outbound, gruu
Event: presence
Expires: 423197357
Content-Type: application/vnd.3gpp.mcptt-info+xml
Content-Length: 320
Contact: <sip:mcx.test-111.iitb@172.27.232.105:44263;transport=udp>;transport=udp;expires=600;+sip.instance="<urn:uuid:168e1fee-0a0f-0038-9ef0-cba44d3df8f7>"
P-Preferred-Identity: sip:mcx.test-111.iitbims.mnc001.mcc001.3gppnetwork.org
P-Preferred-Service: urn:urn-7:3gpp-service.ims.icsi.mcptt
P-Access-Network-Info: ADSL;utran-cell-id-3gpp=00000000
Privacy: none
Accept: application/pidf+xml
User-Agent: NonMCLinphoneAndroid/4.4.0 (Nokia 6.1 Plus) LinphoneSDK/4.5.0-beta.89+4aecab5-debug (pipelines/25895)

<?xml version="1.0" encoding="UTF-8"?>
<mcpttinfo xmlns="urn:3gpp:ns:mcpttInfo:1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<mcptt-Params>
<mcptt-request-uri type="Normal">
<mcpttURI>sip:mcptt.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org</mcpttURI>
</mcptt-request-uri>
</mcptt-Params>
</mcpttinfo>

2021-03-01 11:22:57:642 [org.linphone.debug/liblinphone] MESSAGE LinphoneEvent [0x72a5921c00] moving to subscription state LinphoneSubscriptionOutgoingProgress
2021-03-01 11:22:57:666 [org.linphone.debug/belle-sip] MESSAGE bellesip_wake_lock_acquire(): Android wake lock [belle-sip recv channel] acquired [ref=0x30f2]
2021-03-01 11:22:57:667 [org.linphone.debug/belle-sip] MESSAGE bellesip_wake_lock_acquire(): cast long of wakelock 12530
2021-03-01 11:22:57:667 [org.linphone.debug/belle-sip] MESSAGE channel [0x72a58b5f00]: starting recv background task with id=[30f2].
2021-03-01 11:22:57:667 [org.linphone.debug/belle-sip] MESSAGE channel [0x72a58b5f00]: received [386] new bytes from [UDP://172.31.37.34:7684]:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 172.27.232.105:44263;branch=z9hG4bK.MQV1wJ3DG;rport=44263
From: <sip:mcx.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org>;tag=Ux9dIH7eh
To: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org>;tag=NQNeScF4N15Xe
Call-ID: sVhwxkU8Xr
CSeq: 20 SUBSCRIBE
Contact: <sip:172.31.37.34:7684>
User-Agent: MCLabs Registration Server
Content-Length: 0

NOTIFY sip:mcx.test-111.iitb@172.27.232.105:44263;transport=udp SIP/2.0
Via: SIP/2.0/UDP 172.31.37.34:7684;rport;branch=z9hG4bKS8Xjgv9FDjSSQ
Max-Forwards: 70
From: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org>;tag=p0e7t7Z7javga
To: <sip:mcx.test-111.iitb@172.27.232.105:44263>;transport=udp
Call-ID: sVhwxkU8Xr
CSeq: 32735195 NOTIFY
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mcptt";require;explicit
User-Agent: MCLabs MCX Server
Event: presence
Subscription-State: active;expires=4294967295
Content-Type: application/pidf+xml
Content-Length: 264
P-Asserted-Service: urn:urn-7:3gpp-service.ims.icsi.mcptt
P-Asserted-Identity: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.or>

<?xml version="1.0" encoding="UTF-8"?><presence xmlns="urn:ietf:params:xml:ns:pidf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mcpttPI10="urn:3gpp:ns:mcpttPresInfo:1.0" entity="sip:mcptt.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org"></presence>
```
So as per RFC 3261 we can map NOTIFY request to the Contact address of Sip Subscribe Event ,so out of dialog notify should not occur.
So what exactly is the reason for the rejection of NOTIFY.

**Comment by nick2601** [comment]
@Vish 
I am suppose to get multiple incoming messages from same contact and I want to store those messages in an Arraylist variable upon their arrival ,and for this I am using this code
```
@Override
                    public void onMessageReceived(
                            @NonNull Core core,
                            @NonNull ChatRoom chatRoom,
                            @NonNull ChatMessage message) {
                        super.onMessageReceived(core, chatRoom, message);
                        ArrayList<String> textMessage = new ArrayList<>();
                        String xml=null;
                        UserList userList = null;
                        {
                            for (Content c : message.getContents()) {
                                message.getChatRoom();
                                message.hasTextContent();
                                if (c.isText()) {
                                    textMessage.add(c.getUtf8text);
                                }
                                xml = textMessage.get(0);
                                android.util.Log.d(TAG, xml);
                            }
}
```
Unfortunately,I am not able to read the messages using this method,Can you suggest some other approach in storing the messages in list and retreving values of one message at time depending on their arrival.
Thanks in andvance
