### ISSUE TITLE
Linphone and Raspberry Pi Zero W

### ISSUE THREAD

**Issue by hsmptg** [BelledonneCommunications/linphone-sdk#88]
Hi

In a previous [issue](https://github.com/BelledonneCommunications/linphone-sdk/issues/80) I managed to build linphone-sdk on a Raspberry Pi 4 with the precious help of Viish.

My initial goal was to use linphone on a Raspberry Pi Zero W but when I tried to repeat the same procedure the compiler halted due to probably a lack of memory.

So Viish suggested me [here](https://github.com/BelledonneCommunications/linphone-sdk/issues/80#issuecomment-732091766) to use the python wrapper, what I did but when I run the ```pip3 install pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv7l.whl``` I get the following error:
```
pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv7l.whl is not a supported wheel on this platform.
```
This is understandable since RPi 4 has a armv7l architecture while RPi Zero W has a armv6l architecture.
So the question is: what can I do now?

Regards

**Comment by hsmptg** [comment]
Hi
Sorry to insist but after all the work I (we) did in [another issue](https://github.com/BelledonneCommunications/linphone-sdk/issues/80), I really need to use this in a Raspberry Pi Zero W, instead of giving up and going to another SIP phone solution.
I did not found anything related with this ```.whl is not a supported wheel on this platform``` issue on a Raspberry Pi.
The most similar one was [this](https://stackoverflow.com/questions/43734513/how-to-install-tensorflow-on-raspberry-pi-2) in a tensorflow installation.
Have you any suggestion?
Regards

**Comment by Viish** [comment]
Hi,
If indeed the issue is with the different platform, then either you'll have to build on the RPi ZeroW directly or maybe on another RPi with the same architecture (Pi 3?).
Otherwise you will have to cross compile. It was working for the previous python wrapper a few years ago but I don't think it will work out of the box currently.
Cheers,

**Comment by hsmptg** [comment]
Hi
As I said, I got an error each time I try to install the .whl file that was generated in the Raspberry Pi 4:
```
pi@rpi-zero:~ $ pip install pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv7l.whl
pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv7l.whl is not a supported wheel on this platform.
```
But if I simply change the name of the .whl from ```...armv7l.whl``` to ```...armv6l.whl```, apparently the installation works:
```
pi@rpi-zero:~ $ pip install pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv6l.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./pylinphone-4.5.0a233+git.42fc36a-cp27-cp27mu-linux_armv6l.whl
Installing collected packages: pylinphone
Successfully installed pylinphone-4.5.0a233+git.42fc36a
```
Note that if I use pip3 instead of pip, whatever the name of the .whl file I use, I get the initial error!

But then, after this apparent success, if I try to import the package linphone, I get this:
```
pi@rpi-zero:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import linphone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/linphone/__init__.py", line 4, in <module>
    liblinphone_library = CDLL(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
>>>
```
In fact, the libbellesip.so.1 file does not exist but if I list the site-packages/linphone folder I got all these files where one of them is the libbellesip.so:
```
pi@rpi-zero:~ $ ls -la /home/pi/.local/lib/python2.7/site-packages/linphone
total 187616
drwxr-xr-x 2 pi pi     4096 Nov 26 19:43 .
drwx------ 4 pi pi     4096 Nov 26 19:42 ..
-rw-r--r-- 1 pi pi      164 Nov 26 19:41 __init__.py
-rw-r--r-- 1 pi pi      400 Nov 26 19:42 __init__.pyc
-rw-r--r-- 1 pi pi   229332 Nov 26 19:41 libbcg729.so
-rw-r--r-- 1 pi pi  4363728 Nov 26 19:41 libbctoolbox.so
-rw-r--r-- 1 pi pi    89300 Nov 26 19:41 libbctoolbox-tester.so
-rw-r--r-- 1 pi pi   127356 Nov 26 19:41 libbcunit.so
-rw-r--r-- 1 pi pi 20654064 Nov 26 19:41 libbelcard.so
-rw-r--r-- 1 pi pi 10384988 Nov 26 19:41 libbellesip.so
-rw-r--r-- 1 pi pi  5620136 Nov 26 19:41 libbelr.so
-rw-r--r-- 1 pi pi   140608 Nov 26 19:41 libbv16.so
-rw-r--r-- 1 pi pi   247564 Nov 26 19:41 libbzrtp.so
-rw-r--r-- 1 pi pi   579128 Nov 26 19:41 libdecaf.so
-rw-r--r-- 1 pi pi   129976 Nov 26 19:41 libgsm.so
-rw-r--r-- 1 pi pi 10210292 Nov 26 19:41 liblime.so
-rwxr-xr-x 1 pi pi 90016464 Nov 26 19:41 liblinphone.so
-rwxr-xr-x 1 pi pi  1241272 Nov 26 19:42 libmbedcrypto.so
-rwxr-xr-x 1 pi pi   573812 Nov 26 19:42 libmbedtls.so
-rwxr-xr-x 1 pi pi   277376 Nov 26 19:42 libmbedx509.so
-rw-r--r-- 1 pi pi  7819740 Nov 26 19:42 libmediastreamer.so
-rw-r--r-- 1 pi pi  1139400 Nov 26 19:42 libortp.so
-rw-r--r-- 1 pi pi  6017168 Nov 26 19:42 libsoci_core.so
-rw-r--r-- 1 pi pi  1770184 Nov 26 19:42 libsoci_sqlite3.so
-rw-r--r-- 1 pi pi   307716 Nov 26 19:42 libspeexdsp.so
-rw-r--r-- 1 pi pi   335824 Nov 26 19:42 libspeex.so
-rw-r--r-- 1 pi pi  3538988 Nov 26 19:42 libsqlite3.so
-rw-r--r-- 1 pi pi   399828 Nov 26 19:42 libsrtp2.so
-rw-r--r-- 1 pi pi 21997340 Nov 26 19:42 libxerces-c.so
-rw-r--r-- 1 pi pi  3828408 Nov 26 19:42 libxml2.so
```
Any suggestion on what to try now?
Regards

**Comment by Viish** [comment]
> But if I simply change the name of the .whl from ...armv7l.whl to ...armv6l.whl, apparently the installation works:

Then you are lucky.

> Note that if I use pip3 instead of pip, whatever the name of the .whl file I use, I get the initial error!

That's expected, as the python version number is also in the wheel name. As you built it with python2, it can't be installed by python3. Note that the wrapper is made for python3 even if it may work with python2.

> In fact, the libbellesip.so.1 file does not exist

Indeed, but I don't know why in your case you need it and I don't. Anyway I fixed that, please update to SDK commit 694a959dddeeb6e75bd32a247b7301dcf8228026 and update submodules.

**Comment by hsmptg** [comment]
> Anyway I fixed that, please update to SDK commit [694a959](https://github.com/BelledonneCommunications/linphone-sdk/commit/694a959dddeeb6e75bd32a247b7301dcf8228026)...

Hi
I tried to do that by running:
```
pi@rpi-4gb:~/linphone-sdk $ git checkout 694a959
error: pathspec '694a959' did not match any file(s) known to git

pi@rpi-4gb:~/linphone-sdk $ git checkout 694a959dddeeb6e75bd32a247b7301dcf8228026
fatal: reference is not a tree: 694a959dddeeb6e75bd32a247b7301dcf8228026

pi@rpi-4gb:~/linphone-sdk $ git checkout -b feature/python_wrapper 694a959dddeeb6e75bd32a247b7301dcf8228026
fatal: reference is not a tree: 694a959dddeeb6e75bd32a247b7301dcf8228026
```
But as you can see, all failed.
Can you tell me how to do it properly?
Regards

**Comment by Viish** [comment]
Yes, I made changes this morning so here's the current hash: 521def02ec7de6161981e8847d85421c2e492f8b
Another way is to delete your local branch, fetch and re-checkout the branch.

**Comment by hsmptg** [comment]
Hi
I used this last commit and obtained a new .whl file, but unfortunately the problem remains:
```
pi@rpi-zero:~ $ pip install pylinphone-4.5.0a253+git.521def0-cp27-cp27mu-linux_armv6l.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./pylinphone-4.5.0a253+git.521def0-cp27-cp27mu-linux_armv6l.whl
Installing collected packages: pylinphone
  Found existing installation: pylinphone 4.5.0a233+git.42fc36a
    Uninstalling pylinphone-4.5.0a233+git.42fc36a:
      Successfully uninstalled pylinphone-4.5.0a233+git.42fc36a
Successfully installed pylinphone-4.5.0a253+git.521def0

pi@rpi-zero:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import linphone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/linphone/__init__.py", line 4, in <module>
    liblinphone_library = CDLL(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
>>> exit()

pi@rpi-zero:~ $ ls -la /home/pi/.local/lib/python2.7/site-packages/linphone
total 187616
drwxr-xr-x 2 pi pi     4096 Nov 27 12:27 .
drwx------ 4 pi pi     4096 Nov 27 12:26 ..
-rw-r--r-- 1 pi pi      164 Nov 27 12:25 __init__.py
-rw-r--r-- 1 pi pi      400 Nov 27 12:26 __init__.pyc
-rw-r--r-- 1 pi pi   229332 Nov 27 12:25 libbcg729.so
-rw-r--r-- 1 pi pi  4363728 Nov 27 12:25 libbctoolbox.so
-rw-r--r-- 1 pi pi    89300 Nov 27 12:25 libbctoolbox-tester.so
-rw-r--r-- 1 pi pi   127356 Nov 27 12:25 libbcunit.so
-rw-r--r-- 1 pi pi 20654064 Nov 27 12:25 libbelcard.so
-rw-r--r-- 1 pi pi 10384988 Nov 27 12:25 libbellesip.so
-rw-r--r-- 1 pi pi  5620136 Nov 27 12:25 libbelr.so
-rw-r--r-- 1 pi pi   140608 Nov 27 12:25 libbv16.so
-rw-r--r-- 1 pi pi   247564 Nov 27 12:25 libbzrtp.so
-rw-r--r-- 1 pi pi   579128 Nov 27 12:25 libdecaf.so
-rw-r--r-- 1 pi pi   129976 Nov 27 12:25 libgsm.so
-rw-r--r-- 1 pi pi 10210292 Nov 27 12:25 liblime.so
-rwxr-xr-x 1 pi pi 90016464 Nov 27 12:26 liblinphone.so
-rwxr-xr-x 1 pi pi  1241272 Nov 27 12:26 libmbedcrypto.so
-rwxr-xr-x 1 pi pi   573812 Nov 27 12:26 libmbedtls.so
-rwxr-xr-x 1 pi pi   277376 Nov 27 12:26 libmbedx509.so
-rw-r--r-- 1 pi pi  7819740 Nov 27 12:26 libmediastreamer.so
-rw-r--r-- 1 pi pi  1139400 Nov 27 12:26 libortp.so
-rw-r--r-- 1 pi pi  6017168 Nov 27 12:26 libsoci_core.so
-rw-r--r-- 1 pi pi  1770184 Nov 27 12:26 libsoci_sqlite3.so
-rw-r--r-- 1 pi pi   307716 Nov 27 12:26 libspeexdsp.so
-rw-r--r-- 1 pi pi   335824 Nov 27 12:26 libspeex.so
-rw-r--r-- 1 pi pi  3538988 Nov 27 12:26 libsqlite3.so
-rw-r--r-- 1 pi pi   399828 Nov 27 12:26 libsrtp2.so
-rw-r--r-- 1 pi pi 21997340 Nov 27 12:26 libxerces-c.so
-rw-r--r-- 1 pi pi  3828408 Nov 27 12:26 libxml2.so
```
Any suggestion on what to try now?
Regards

**Comment by Viish** [comment]
Have you cleaned your build folder and built from scratch? If not, do it.

**Comment by hsmptg** [comment]
You are referring to the build folder at the Raspberry Pi 4 where I generated the new .whl file, right?
Well, I think so since I renamed my older build_raspberry folder and created a new one, and was from inside this new one that I ran the cmake and make commands.
But I can repeat all the process in a fresh Raspberry Pi 4.

Meanwhile I inpected the ```__init__.py``` file that caused the error and checked that the problem is in fact in the line:
```
liblinphone_library = CDLL(lib_path)
```
Since I confirmed that lib_path variable is equal to:
```
/home/pi/.local/lib/python2.7/site-packages/linphone/liblinphone.so
```
And when I try to call the CDLL with it I get the error:
```
pi@rpi-zero:~/.local/lib/python2.7/site-packages/linphone $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import CDLL
>>> mylib = CDLL('/home/pi/.local/lib/python2.7/site-packages/linphone/liblinphone.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
>>>
```

**Comment by Viish** [comment]
Also if issue persists check you have the libbellesip.so.1 in `<build dir>/WORK/desktop/Build/linphone/wrappers/python/linphone` and that in `linphone-sdk/liblinphone/wrappers/python/setup.cmake` you have `package_data={'linphone': ['*.so*']}`

**Comment by hsmptg** [comment]
The setup.cmake I have do not include the last * in the line you mention:
```
pi@rpi-4gb:~/linphone-sdk/liblinphone/wrappers/python $ cat setup.cmake
from setuptools import setup, Distribution
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

linphone_extension = Extension(
    name="pylinphone",
    sources=["pylinphone.pyx"],
    libraries=["@LINPHONE_LIBRARY_NAME@", "@BCTOOLBOX_CORE_LIBRARIES@", "@BELLESIP_LIBRARIES@"],
    language="c",
    library_dirs=["@PROJECT_BINARY_DIR@/src", "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"],
    include_dirs=["@PROJECT_SOURCE_DIR@/include", "@BELLESIP_INCLUDE_DIRS@", "@BCTOOLBOX_INCLUDE_DIRS@"]
)

class BinaryDistribution(Distribution):
    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False

setup(
    ext_modules = cythonize([linphone_extension], compiler_directives={'language_level' : "3"}),
    name="pylinphone",
    version="@WHEEL_LINPHONESDK_VERSION@",
    author="Belledonne Communications",
    author_email="info@belledonne-communications.com",
    description="A python wrapper for linphone library",
    long_description="A python wrapper for linphone library automatically generated using Cython",
    long_description_content_type="plain/text",
    url="https://linphone.org",
    license="GPLv3",
    packages=['linphone'],
    package_data={'linphone': ['*.so']},
    distclass=BinaryDistribution
)
```
I assume that is the reason for the .so.1 file not being included, right?
Now I remember that I probably I did not updated the submodules!
Shame on me! Sorry!!! :/

After doing that I already have the * and rebuilding once again:
```
pi@rpi-zero:~ $ pip3 install pylinphone-4.5.0a253+git.521def0-cp37-cp37m-linux_armv6l.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./pylinphone-4.5.0a253+git.521def0-cp37-cp37m-linux_armv6l.whl
Installing collected packages: pylinphone
Successfully installed pylinphone-4.5.0a253+git.521def0
```
This time in the Raspberry Pi Zero, I need to use pip3 (because of the cp37, right?) but with the .whl renamed to ...armv6l.whl.
But when I try once again to make the ```import linphone``` test...
```
pi@rpi-zero:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import linphone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/linphone/__init__.py", line 4, in <module>
    liblinphone_library = CDLL(lib_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
>>>
```
No libbellesip.so.1??? Again?!?
But now I have it:
```
pi@rpi-zero:~ $ ls -la /home/pi/.local/lib/python3.7/site-packages/linphone
total 271644
drwxr-xr-x 3 pi pi     4096 Nov 27 14:51 .
drwx------ 4 pi pi     4096 Nov 27 14:49 ..
-rw-r--r-- 1 pi pi      164 Nov 27 14:47 __init__.py
-rw-r--r-- 1 pi pi   229332 Nov 27 14:47 libbcg729.so
-rw-r--r-- 1 pi pi   229332 Nov 27 14:47 libbcg729.so.0
-rw-r--r-- 1 pi pi  4363728 Nov 27 14:47 libbctoolbox.so
-rw-r--r-- 1 pi pi  4363728 Nov 27 14:47 libbctoolbox.so.1
-rw-r--r-- 1 pi pi    89616 Nov 27 14:47 libbctoolbox-tester.so
-rw-r--r-- 1 pi pi    89616 Nov 27 14:47 libbctoolbox-tester.so.1
-rw-r--r-- 1 pi pi   127356 Nov 27 14:47 libbcunit.so
-rw-r--r-- 1 pi pi   127356 Nov 27 14:47 libbcunit.so.1.0.1
-rw-r--r-- 1 pi pi 20654064 Nov 27 14:47 libbelcard.so
-rw-r--r-- 1 pi pi 20654064 Nov 27 14:48 libbelcard.so.1
-rw-r--r-- 1 pi pi 10385532 Nov 27 14:48 libbellesip.so
-rw-r--r-- 1 pi pi 10385532 Nov 27 14:48 libbellesip.so.1
-rw-r--r-- 1 pi pi  5620136 Nov 27 14:48 libbelr.so
-rw-r--r-- 1 pi pi  5620136 Nov 27 14:48 libbelr.so.1
-rw-r--r-- 1 pi pi   140608 Nov 27 14:48 libbv16.so
-rw-r--r-- 1 pi pi   247564 Nov 27 14:48 libbzrtp.so
-rw-r--r-- 1 pi pi   247564 Nov 27 14:48 libbzrtp.so.0
-rw-r--r-- 1 pi pi   579128 Nov 27 14:48 libdecaf.so
-rw-r--r-- 1 pi pi   579128 Nov 27 14:48 libdecaf.so.0
-rw-r--r-- 1 pi pi   129976 Nov 27 14:48 libgsm.so
-rw-r--r-- 1 pi pi 10210292 Nov 27 14:48 liblime.so
-rw-r--r-- 1 pi pi 10210292 Nov 27 14:48 liblime.so.0
-rwxr-xr-x 1 pi pi 89896600 Nov 27 14:48 liblinphone.so
-rwxr-xr-x 1 pi pi  1241272 Nov 27 14:48 libmbedcrypto.so
-rwxr-xr-x 1 pi pi  1241272 Nov 27 14:48 libmbedcrypto.so.2.16.6
-rwxr-xr-x 1 pi pi  1241272 Nov 27 14:48 libmbedcrypto.so.3
-rwxr-xr-x 1 pi pi   573812 Nov 27 14:48 libmbedtls.so
-rwxr-xr-x 1 pi pi   573812 Nov 27 14:48 libmbedtls.so.12
-rwxr-xr-x 1 pi pi   573812 Nov 27 14:48 libmbedtls.so.2.16.6
-rwxr-xr-x 1 pi pi   277376 Nov 27 14:48 libmbedx509.so
-rwxr-xr-x 1 pi pi   277376 Nov 27 14:48 libmbedx509.so.0
-rwxr-xr-x 1 pi pi   277376 Nov 27 14:48 libmbedx509.so.2.16.6
-rw-r--r-- 1 pi pi  7819756 Nov 27 14:48 libmediastreamer.so
-rw-r--r-- 1 pi pi  7819756 Nov 27 14:48 libmediastreamer.so.11
-rw-r--r-- 1 pi pi  1139400 Nov 27 14:48 libortp.so
-rw-r--r-- 1 pi pi  1139400 Nov 27 14:48 libortp.so.15
-rw-r--r-- 1 pi pi  6017168 Nov 27 14:48 libsoci_core.so
-rw-r--r-- 1 pi pi  6017168 Nov 27 14:48 libsoci_core.so.4.0
-rw-r--r-- 1 pi pi  6017168 Nov 27 14:48 libsoci_core.so.4.0.0
-rw-r--r-- 1 pi pi  1770184 Nov 27 14:48 libsoci_sqlite3.so
-rw-r--r-- 1 pi pi  1770184 Nov 27 14:49 libsoci_sqlite3.so.4.0
-rw-r--r-- 1 pi pi  1770184 Nov 27 14:49 libsoci_sqlite3.so.4.0.0
-rw-r--r-- 1 pi pi   307716 Nov 27 14:49 libspeexdsp.so
-rw-r--r-- 1 pi pi   307716 Nov 27 14:49 libspeexdsp.so.6
-rw-r--r-- 1 pi pi   335824 Nov 27 14:49 libspeex.so
-rw-r--r-- 1 pi pi   335824 Nov 27 14:49 libspeex.so.6
-rw-r--r-- 1 pi pi  3538988 Nov 27 14:49 libsqlite3.so
-rw-r--r-- 1 pi pi   399828 Nov 27 14:49 libsrtp2.so
-rw-r--r-- 1 pi pi   399828 Nov 27 14:49 libsrtp2.so.2
-rw-r--r-- 1 pi pi 21997340 Nov 27 14:49 libxerces-c.so
-rw-r--r-- 1 pi pi  3828408 Nov 27 14:49 libxml2.so
-rw-r--r-- 1 pi pi  3828408 Nov 27 14:49 libxml2.so.2
drwxr-xr-x 2 pi pi     4096 Nov 27 14:51 __pycache__
```
Once again, if I try to run the CDLL python line of ```__init__.py``` I get the same error:
```
pi@rpi-zero:~ $ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import CDLL
>>> mylib = CDLL('/home/pi/.local/lib/python3.7/site-packages/linphone/liblinphone.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
>>>
```
What do you suggest now?

**Comment by Viish** [comment]
Make sure you aren't in the linphone-sdk directory or any of it's sub directory when doing the `python3 -c "import linphone"`.
You can also try to remove your python2 package just in case.
Finally try the following and copy/paste here the results:
`ldd ~/.local/lib/python3.7/site-packages/linphone/liblinphone.so`

**Comment by hsmptg** [comment]
As you can see I did the command in my pi home directory:
```
pi@rpi-zero:~ $ python3 -c "import linphone"
------>
/home/pi/.local/lib/python3.7/site-packages/linphone/liblinphone.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/linphone/__init__.py", line 6, in <module>
    liblinphone_library = CDLL(lib_path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbellesip.so.1: cannot open shared object file: No such file or directory
```
My linphone python2 package is now empty, and now I even deleted it.

The results of your line are the following:
```
pi@rpi-zero:~ $ ldd ~/.local/lib/python3.7/site-packages/linphone/liblinphone.so
        /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so (0xb6ada000)
        libbellesip.so.1 => not found
        libbelr.so.1 => not found
        libmediastreamer.so.11 => not found
        libortp.so.15 => not found
        libxml2.so.2 => /usr/lib/arm-linux-gnueabihf/libxml2.so.2 (0xb695d000)
        libxerces-c.so => not found
        liblime.so.0 => not found
        libsoci_core.so.4.0 => not found
        libsqlite3.so => not found
        libbelcard.so.1 => not found
        libbctoolbox.so.1 => not found
        libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb6816000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6794000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6767000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6619000)
        /lib/ld-linux-armhf.so.3 (0xb6f86000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6606000)
        libicui18n.so.63 => /usr/lib/arm-linux-gnueabihf/libicui18n.so.63 (0xb63b8000)
        libicuuc.so.63 => /usr/lib/arm-linux-gnueabihf/libicuuc.so.63 (0xb6232000)
        libicudata.so.63 => /usr/lib/arm-linux-gnueabihf/libicudata.so.63 (0xb4834000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb4809000)
        liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0xb47d8000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb47ae000)
```
Well?

**Comment by Viish** [comment]
Ok it seems there is indeed an issue with my wheel and the way shared libraries path are computed.
I can reproduce the issue on my build computer if I rename or move the linphone-sdk directory...
I'll let you know when I'll have a fix.

**Comment by Viish** [comment]
In the meantime, you can create on your pi zero the same directory tree that on your build raspberry and put there the libraries, for example `/home/pi/linphone-sdk/build/linphone-sdk/desktop/lib64/`

**Comment by hsmptg** [comment]
> I'll let you know when I'll have a fix.

OK, thanks!!!

> In the meantime, you can create on your pi zero the same directory tree that on your build raspberry and put there the libraries, for example `/home/pi/linphone-sdk/build/linphone-sdk/desktop/lib64/`

I believe you mean this:
```
pi@rpi-4gb:~ $ scp /home/pi/linphone-sdk/build-raspberry/linphone-sdk/desktop/lib/* pi@10.0.5.86:/home/pi/.local/lib/python3.7/site-packages/linphone           pi@10.0.5.86's password:
/home/pi/linphone-sdk/build-raspberry/linphone-sdk/desktop/lib/cmake: not a regular file
libbcg729.so                                  100%  224KB   1.7MB/s   00:00
libbcg729.so.0                                100%  224KB   2.3MB/s   00:00
libbctoolbox.so                               100% 4261KB   3.1MB/s   00:01
libbctoolbox.so.1                             100% 4261KB   3.0MB/s   00:01
libbctoolbox-tester.so                        100%   88KB   2.5MB/s   00:00
libbctoolbox-tester.so.1                      100%   88KB   2.4MB/s   00:00
libbcunit.so                                  100%  124KB   2.5MB/s   00:00
libbcunit.so.1.0.1                            100%  124KB   2.9MB/s   00:00
libbelcard.so                                 100%   20MB   1.2MB/s   00:16
libbelcard.so.1                               100%   20MB   3.0MB/s   00:06
libbellesip.so                                100%   10MB   1.9MB/s   00:05
libbellesip.so.1                              100%   10MB   1.1MB/s   00:09
libbelr.so                                    100% 5488KB   2.7MB/s   00:01
libbelr.so.1                                  100% 5488KB   2.8MB/s   00:01
libbv16.so                                    100%  137KB   2.3MB/s   00:00
libbzrtp.so                                   100%  242KB   1.9MB/s   00:00
libbzrtp.so.0                                 100%  242KB   2.6MB/s   00:00
libdecaf.so                                   100%  566KB   3.2MB/s   00:00
libdecaf.so.0                                 100%  566KB   2.6MB/s   00:00
libgsm.so                                     100%  127KB   2.2MB/s   00:00
liblime.so                                    100% 9971KB 425.8KB/s   00:23
liblime.so.0                                  100% 9971KB   2.7MB/s   00:03
liblinphone++.so                              100% 7328KB   2.9MB/s   00:02
liblinphone.so                                100%   86MB   2.6MB/s   00:32
liblinphone++.so.10                           100% 7328KB   2.6MB/s   00:02
liblinphone.so.10                             100%   86MB   2.1MB/s   00:40
libmbedcrypto.so                              100% 1212KB   2.3MB/s   00:00
libmbedcrypto.so.2.16.6                       100% 1212KB   2.4MB/s   00:00
libmbedcrypto.so.3                            100% 1212KB   2.4MB/s   00:00
libmbedtls.so                                 100%  560KB   3.2MB/s   00:00
libmbedtls.so.12                              100%  560KB   2.7MB/s   00:00
libmbedtls.so.2.16.6                          100%  560KB   3.0MB/s   00:00
libmbedx509.so                                100%  271KB   3.2MB/s   00:00
libmbedx509.so.0                              100%  271KB   2.7MB/s   00:00
libmbedx509.so.2.16.6                         100%  271KB   3.2MB/s   00:00
libmediastreamer.so                           100% 7636KB   2.6MB/s   00:02
libmediastreamer.so.11                        100% 7636KB   2.6MB/s   00:02
libortp.so                                    100% 1113KB   2.3MB/s   00:00
libortp.so.15                                 100% 1113KB   2.5MB/s   00:00
libsoci_core.so                               100% 5876KB   2.8MB/s   00:02
libsoci_core.so.4.0                           100% 5876KB   1.1MB/s   00:05
libsoci_core.so.4.0.0                         100% 5876KB   1.5MB/s   00:03
libsoci_sqlite3.so                            100% 1729KB   1.7MB/s   00:00
libsoci_sqlite3.so.4.0                        100% 1729KB 395.3KB/s   00:04
libsoci_sqlite3.so.4.0.0                      100% 1729KB   2.4MB/s   00:00
libspeexdsp.so                                100%  301KB  57.2KB/s   00:05
libspeexdsp.so.6                              100%  301KB  50.1KB/s   00:06
libspeex.so                                   100%  328KB   2.5MB/s   00:00
libspeex.so.6                                 100%  328KB   2.4MB/s   00:00
libsqlite3.so                                 100% 3456KB   2.6MB/s   00:01
libsrtp2.so                                   100%  390KB   3.0MB/s   00:00
libsrtp2.so.2                                 100%  390KB   3.2MB/s   00:00
libturbojpeg.a                                100% 2731KB   2.4MB/s   00:01
libxerces-c.so                                100%   21MB   2.2MB/s   00:09
libxml2.so                                    100% 3739KB   3.6MB/s   00:01
libxml2.so.2                                  100% 3739KB 509.0KB/s   00:07
libyuv.a                                      100% 1365KB   2.4MB/s   00:00
libz.a                                        100%  313KB   2.6MB/s   00:00
/home/pi/linphone-sdk/build-raspberry/linphone-sdk/desktop/lib/mediastreamer: not a regular file
/home/pi/linphone-sdk/build-raspberry/linphone-sdk/desktop/lib/pkgconfig: not a regular file
```
Now in my Raspberry Pi Zero I have a set of more libs:
```
pi@rpi-zero:~ $ ls -la ~/.local/lib/python3.7/site-packages/linphone
total 378516
drwxr-xr-x 3 pi pi     4096 Nov 27 15:48 .
drwx------ 5 pi pi     4096 Nov 27 15:41 ..
-rw-r--r-- 1 pi pi      198 Nov 27 15:01 __init__.py
-rw-r--r-- 1 pi pi   229332 Nov 27 15:45 libbcg729.so
-rw-r--r-- 1 pi pi   229332 Nov 27 15:45 libbcg729.so.0
-rw-r--r-- 1 pi pi  4363728 Nov 27 15:45 libbctoolbox.so
-rw-r--r-- 1 pi pi  4363728 Nov 27 15:45 libbctoolbox.so.1
-rw-r--r-- 1 pi pi    89616 Nov 27 15:45 libbctoolbox-tester.so
-rw-r--r-- 1 pi pi    89616 Nov 27 15:45 libbctoolbox-tester.so.1
-rw-r--r-- 1 pi pi   127356 Nov 27 15:45 libbcunit.so
-rw-r--r-- 1 pi pi   127356 Nov 27 15:45 libbcunit.so.1.0.1
-rw-r--r-- 1 pi pi 20654064 Nov 27 15:45 libbelcard.so
-rw-r--r-- 1 pi pi 20654064 Nov 27 15:45 libbelcard.so.1
-rw-r--r-- 1 pi pi 10385532 Nov 27 15:45 libbellesip.so
-rw-r--r-- 1 pi pi 10385532 Nov 27 15:45 libbellesip.so.1
-rw-r--r-- 1 pi pi  5620136 Nov 27 15:45 libbelr.so
-rw-r--r-- 1 pi pi  5620136 Nov 27 15:46 libbelr.so.1
-rw-r--r-- 1 pi pi   140608 Nov 27 15:46 libbv16.so
-rw-r--r-- 1 pi pi   247564 Nov 27 15:46 libbzrtp.so
-rw-r--r-- 1 pi pi   247564 Nov 27 15:46 libbzrtp.so.0
-rw-r--r-- 1 pi pi   579128 Nov 27 15:46 libdecaf.so
-rw-r--r-- 1 pi pi   579128 Nov 27 15:46 libdecaf.so.0
-rw-r--r-- 1 pi pi   129976 Nov 27 15:46 libgsm.so
-rw-r--r-- 1 pi pi 10210292 Nov 27 15:46 liblime.so
-rw-r--r-- 1 pi pi 10210292 Nov 27 15:46 liblime.so.0
-rw-r--r-- 1 pi pi  7503904 Nov 27 15:46 liblinphone++.so
-rwxr-xr-x 1 pi pi 89896600 Nov 27 15:47 liblinphone.so
-rw-r--r-- 1 pi pi  7503904 Nov 27 15:47 liblinphone++.so.10
-rw-r--r-- 1 pi pi 89896600 Nov 27 15:47 liblinphone.so.10
-rwxr-xr-x 1 pi pi  1241272 Nov 27 15:47 libmbedcrypto.so
-rwxr-xr-x 1 pi pi  1241272 Nov 27 15:47 libmbedcrypto.so.2.16.6
-rwxr-xr-x 1 pi pi  1241272 Nov 27 15:47 libmbedcrypto.so.3
-rwxr-xr-x 1 pi pi   573812 Nov 27 15:47 libmbedtls.so
-rwxr-xr-x 1 pi pi   573812 Nov 27 15:47 libmbedtls.so.12
-rwxr-xr-x 1 pi pi   573812 Nov 27 15:47 libmbedtls.so.2.16.6
-rwxr-xr-x 1 pi pi   277376 Nov 27 15:47 libmbedx509.so
-rwxr-xr-x 1 pi pi   277376 Nov 27 15:47 libmbedx509.so.0
-rwxr-xr-x 1 pi pi   277376 Nov 27 15:47 libmbedx509.so.2.16.6
-rw-r--r-- 1 pi pi  7819756 Nov 27 15:47 libmediastreamer.so
-rw-r--r-- 1 pi pi  7819756 Nov 27 15:47 libmediastreamer.so.11
-rw-r--r-- 1 pi pi  1139400 Nov 27 15:47 libortp.so
-rw-r--r-- 1 pi pi  1139400 Nov 27 15:47 libortp.so.15
-rw-r--r-- 1 pi pi  6017168 Nov 27 15:47 libsoci_core.so
-rw-r--r-- 1 pi pi  6017168 Nov 27 15:48 libsoci_core.so.4.0
-rw-r--r-- 1 pi pi  6017168 Nov 27 15:48 libsoci_core.so.4.0.0
-rw-r--r-- 1 pi pi  1770184 Nov 27 15:48 libsoci_sqlite3.so
-rw-r--r-- 1 pi pi  1770184 Nov 27 15:48 libsoci_sqlite3.so.4.0
-rw-r--r-- 1 pi pi  1770184 Nov 27 15:48 libsoci_sqlite3.so.4.0.0
-rw-r--r-- 1 pi pi   307716 Nov 27 15:48 libspeexdsp.so
-rw-r--r-- 1 pi pi   307716 Nov 27 15:48 libspeexdsp.so.6
-rw-r--r-- 1 pi pi   335824 Nov 27 15:48 libspeex.so
-rw-r--r-- 1 pi pi   335824 Nov 27 15:48 libspeex.so.6
-rw-r--r-- 1 pi pi  3538988 Nov 27 15:48 libsqlite3.so
-rw-r--r-- 1 pi pi   399828 Nov 27 15:48 libsrtp2.so
-rw-r--r-- 1 pi pi   399828 Nov 27 15:48 libsrtp2.so.2
-rw-r--r-- 1 pi pi  2796678 Nov 27 15:48 libturbojpeg.a
-rw-r--r-- 1 pi pi 21997340 Nov 27 15:48 libxerces-c.so
-rw-r--r-- 1 pi pi  3828408 Nov 27 15:48 libxml2.so
-rw-r--r-- 1 pi pi  3828408 Nov 27 15:48 libxml2.so.2
-rw-r--r-- 1 pi pi  1397364 Nov 27 15:48 libyuv.a
-rw-r--r-- 1 pi pi   320050 Nov 27 15:48 libz.a
drwxr-xr-x 2 pi pi     4096 Nov 27 15:01 __pycache__
```
But the problem remains since I probably did not executed what you wanted, right?
Take your time, I will wait...

But is strange to have an ```libbellesip.so.1: cannot open shared object file: No such file or directory``` error and the ldd saying that it is "not found" when that file (since the setup.cmake correction) is present in the ~/.local/lib/python3.7/site-packages/linphone folder!?!

**Comment by hsmptg** [comment]
Hi
Just to say that meanwhile I found [here](https://pypi.org/project/linphone4raspberry/#files) an .whl old version of this linphone python wrapper:
```
linphone4raspberry-3.9.0-cp27-none-any.whl
```
It is funny because this one do not have a specific architecture (linux_armv6l or linux_armv7l) but it has "none_any" instead. I wonder how/where it was build?

It can be installed on the Zero without any problem:
```
pi@rpi-zero:~ $ pip install linphone4raspberry-3.9.0-cp27-none-any.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./linphone4raspberry-3.9.0-cp27-none-any.whl
Installing collected packages: linphone4raspberry
Successfully installed linphone4raspberry-3.9.0
```
And finally when I use it, this time I got no errors:
```
pi@rpi-zero:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import linphone
>>>
```
This 3.9.0 version is not exactly the one which documentation can be seen [here](https://pythonhosted.org/linphone/) (v3.9.1), but I presume that the differences are not too big, right?
Regards

**Comment by Viish** [comment]
Hi,
Version 3.9.1 is 5 years old so yes a lot has changed. 
Regarding the python wrapper itself, it was the first version which has been dead for years now, and the new one is completely different.
And the packaging of this old python wrapper was made by one of our engineers that left our company, so I can't ask for it's help...

**Comment by hsmptg** [comment]
Hi

During this weekend I used the v3.9.1 wrapper to build my SIP phone in the Raspberry Pi Zero W. For now I only used audio but all worked well! Now I will try audio+video in a Raspberry Pi 3 with a Raspberry camera. I am very confident that it will work too. So, for my needs, this old version wrapper seems to be enough.

Of course it would be nice to have a more recent version working like this v4.5.0. So if you find a way of making it work, that would be great! The way I managed installing the .whl by renaming it from armv7l to armv6l indicates that something is wrong. I wonder how the v3.9.1 .whl was generated since it seems to be agnostic in terms of architecture by saying "none-any" instead!

Regards and any further suggestion to resurrect the old v3.9.1 wrapper into a new v4.5.0 wrapper will be welcome.

**Comment by hsmptg** [comment]
Hi
Just to confirm that the v3.9.1 wrapper worked well also with video. I just had some difficulties in rotating the camera image using the [core.device_rotation](https://pythonhosted.org/linphone/api_reference.html?highlight=rotation#linphone.Core.device_rotation). I never managed to rotate the image that way so I used this command from the cli: ```v4l2-ctl --set-ctrl vertical_flip=1```.
Therefore, you can close this issue #88 if you want to.
It was not the perfect finish since I would prefer to use a new v4.5 wrapper but at least I can do all what I needed.
Thanks for all your help.

**Comment by FrancescoTalotta** [comment]
Hello, I tried to compile on a Raspberry Pi Zero with 
`cmake .. -DENABLE_OPENH264=ON -DENABLE_WEBRTC_AEC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_MKV=OFF -DENABLE_FFMPEG=ON -DENABLE_CXX_WRAPPER=OFF -DENABLE_NON_FREE_CODECS=ON -DENABLE_VCARD=OFF -DENABLE_OPUS=OFF -DENABLE_VPX=OFF -DENABLE_BV16=OFF -DENABLE_V4L=OFF -DCMAKE_INSTALL_PREFIX=/home/pi/linphone/`

however I get this error:

`[ 66%] Building C object src/CMakeFiles/mediastreamer.dir/videofilters/videodec.c.o
In file included from /home/pi/Downloads/linphone-sdk/mediastreamer2/src/videofilters/videodec.c:29:
/home/pi/Downloads/linphone-sdk/mediastreamer2/src/videofilters/videodec.c: In function ‘dec_uninit’:
/home/pi/Downloads/linphone-sdk/mediastreamer2/src/utils/ffmpeg-priv.h:146:23: error: implicit declaration of function ‘avcodec_free_frame’; did you mean ‘avcodec_alloc_frame’? [-Werror=implicit-function-declaration]
 #define av_frame_free avcodec_free_frame
                       ^~~~~~~~~~~~~~~~~~
/home/pi/Downloads/linphone-sdk/mediastreamer2/src/videofilters/videodec.c:118:3: note: in expansion of macro ‘av_frame_free’
   av_frame_free(&s->orig);
   ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[8]: *** [src/CMakeFiles/mediastreamer.dir/build.make:1246: src/CMakeFiles/mediastreamer.dir/videofilters/videodec.c.o] Error 1
make[7]: *** [CMakeFiles/Makefile2:280: src/CMakeFiles/mediastreamer.dir/all] Error 2
make[6]: *** [Makefile:130: all] Error 2
make[5]: *** [CMakeFiles/EP_ms2.dir/build.make:123: /home/pi/Downloads/linphone-sdk/build-raspberry/WORK/desktop/Stamp/EP_ms2/EP_ms2-build] Error 2
make[4]: *** [CMakeFiles/Makefile2:168: CMakeFiles/EP_ms2.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [CMakeFiles/sdk.dir/build.make:113: sdk-prefix/src/sdk-stamp/sdk-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sdk.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

Any idea on how to solve that?

**Comment by FrancescoTalotta** [comment]
Hello, I was able to compile linphonec version 4.5.0 on a raspberry pi zero using the command:

`cmake .. -DENABLE_OPENH264=ON -DENABLE_WEBRTC_AEC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_MKV=OFF -DENABLE_FFMPEG=OFF -DENABLE_CXX_WRAPPER=OFF -DENABLE_NON_FREE_CODECS=ON -DENABLE_VCARD=OFF -DENABLE_OPUS=OFF -DENABLE_VPX=OFF -DENABLE_BV16=OFF -DENABLE_V4L=OFF -DCMAKE_INSTALL_PREFIX=/home/pi/linphone/`

However when I check all the available commands on the linphonec prompt I don't see the `register` and `unregister` commands. Maybe I skipped something in the cmake command?
